version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: loadsql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Happy
      MYSQL_DATABASE: loadDB
      MYSQL_USER: user1
      MYSQL_PASSWORD: Robotsdocker-compose up -d

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
